name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print "Hello, CI!" to logs
        run: echo "Hello, CI!"

      - name: Set up C++ environment
        run: sudo apt update && sudo apt install -y g++ 

      - name: Compile C++ code
        run: g++ -o hello hello.cpp

      - name: Archive executable
        uses: actions/upload-artifact@v4  # Add the correct action version here
        with:
          name: hello-executable
          path: ./hello  # path to the compiled executable

